// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFjQ8xLPkOR7EqN-sbu8c2UJslyYpaXD0',
    appId: '1:514459263466:web:f16b0ca33cf3bd8ff85293',
    messagingSenderId: '514459263466',
    projectId: 'gabimaps-ad5d6',
    authDomain: 'gabimaps-ad5d6.firebaseapp.com',
    storageBucket: 'gabimaps-ad5d6.firebasestorage.app',
    measurementId: 'G-Z35BGWSKXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTyVJtRKoVp2RUIBKDSACwqev27hKzL9Y',
    appId: '1:514459263466:android:fa495253312abdc0f85293',
    messagingSenderId: '514459263466',
    projectId: 'gabimaps-ad5d6',
    storageBucket: 'gabimaps-ad5d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEqbUaUfjb6m5PhHqgq_ICAWkY-MNN4bM',
    appId: '1:514459263466:ios:b317a28a2dc88d9cf85293',
    messagingSenderId: '514459263466',
    projectId: 'gabimaps-ad5d6',
    storageBucket: 'gabimaps-ad5d6.firebasestorage.app',
    iosBundleId: 'com.example.gabimaps',
  );
}
